# Action to generate metrics using LowLighter/Metrics by Simon Lecoq

# All results are in SVG format, and commited to /assets/metrics/ in master branch.
# Split into multiple jobs, to prevent everything failing if one component errors,
# And to improve the loading and layout of /METRICS.md where the SVGs are displayed

name: 📊 Generates Metrics
on:
  schedule:
    - cron: '40 23 * * *' # Run every evening, twenty mins before midnight
  workflow_dispatch: # Or when it's manually triggered
jobs:        
  # Sponsors Card
  sponsor-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/sponsors.svg
          committer_message: "📊 Updates metrics - sponsors"
          # Options
          user: araguaci
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 36
  
  # 10 Years worth of contribution charts
  historical-contribuitions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/contributions.svg
          committer_message: "📊 Updates metrics - contributions"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_calendar: yes
          plugin_calendar_limit: 10
  
  # Ticket (Issue + PR) Follow Ups
  ticket-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/tickets.svg
          committer_message: "📊 Updates metrics - tickets"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

  
  # Coding Habits
  coding-habits-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/habits.svg
          committer_message: "📊 Updates metrics - habbits"
          user: araguaci
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_days: 28
          plugin_habits_from: 500
          config_timezone: America/Sao_Paulo

  # Total Stargazers
  stargazer-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/stargazers.svg
          committer_message: "📊 Updates metrics - stargazers"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 365

  # Recent Activity
  activity-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/activity.svg
          committer_message: "📊 Updates metrics - activity"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, public

  # Reactions on comments / tickets
  reactions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/reactions.svg
          committer_message: "📊 Updates metrics - reactions"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 800
          plugin_reactions_limit_issues: 800
          plugin_reactions_limit_discussions: 800
          plugin_reactions_limit_discussions_comments: 800
          plugin_reactions_details: percentage, count


  # People who I follow / are following me
  people-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "📊 Updates metrics - people"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/people.svg
          user: araguaci
          base: ""
          plugin_people: yes
          plugin_people_types: followers, following
          

  # Languages that code is written in (probz just JS, yuck)
  language-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/languages.svg
          committer_message: "📊 Updates metrics - languages"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_recent_days: 120
          plugin_languages_other: yes
          plugin_languages_sections: most-used, recently-used

  # Achievments, fake awards showing that i have no life
  acheiment-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/achievements.svg
          committer_message: "📊 Updates metrics - acheivments"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: detailed

  # Notable contributions, if there are any lol
  notable-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/notable.svg
          committer_message: "📊 Updates metrics - notable contribs"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
 
  # Discussion metrics, i like to chat
  discussions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/discussions.svg
          committer_message: "📊 Updates metrics - discussions"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 12
  
  # Gists, basically shit-code saved for later
  gists-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/gists.svg
          committer_message: "📊 Updates metrics - gists"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_gists: yes                 
   
  # Stars on projects i like
  starlists-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/starlists.svg
          committer_message: "📊 Updates metrics - starlists"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 12
          plugin_starlists_limit_repositories: 0
          
  # Introduction, info from profile. Not that anyones interested
  intro-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/intro.svg
          committer_message: "📊 Updates metrics - intro"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_introduction: yes  
          
  # Pinned Repositories
  repository-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/repositories.svg
          committer_message: "📊 Updates metrics - repositories"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: >-
            araguaci/dashy, araguaci/AdGuardian-Term, araguaci/portainer-templates, araguaci/personal-security-checklist,
            araguaci/awesome-privacy, araguaci/go-apod, araguaci/dotfiles,araguaci/email-comparison, araguaci/awesome-selfhosted,
            araguaci/docker-tcpdump, araguaci/devolio,
            araguaci/pax, araguaci/all-the-countries, araguaci/minesweper,
            araguaci/callisto-theme-standard-notes, araguaci/araguaci,
            araguaci/twitter-sentiment-visualisation, araguaci/hasami-shogi, araguaci/nfu,
            araguaci/espanso-config, araguaci/minimal-terminal-prompt,
            araguaci/anti-theft-charge, araguaci/md-cv-maker, araguaci/brewfile,
            araguaci/alicia-sykes-website, araguaci/happy-app, araguaci/conky-system-stats-widget
   
 # Starred Topics
  starred-topics-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/topics.svg
          committer_message: "📊 Updates metrics - topics"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 20
          plugin_topics_mode: icons
            
  # StackOverflow Metrics
  stackoverflow-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/stackoverflow.svg
          committer_message: "📊 Updates metrics - stackoverflow"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 979052
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 5

  # Twitter Metrics
  twitter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/twitter.svg
          committer_message: "📊 Updates metrics - twitter"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_user: Lissy_Sykes
          plugin_tweets_limit: 5

  # RSS Feed
  blog-post-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/blog-posts.svg
          committer_message: "📊 Updates metrics - blog"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_rss: yes
          plugin_rss_source: https://notes.aliciasykes.com/feed
          plugin_rss_limit: 8

  # Wakatime Metrics
  wakatime-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/wakatime.svg
          committer_message: "📊 Updates metrics - wakatime"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_user: liss
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          
  # All Metrics together
  all-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/all.svg
          committer_message: "📊 Updates metrics - all"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: araguaci
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
          plugin_traffic: yes
          plugin_gists: yes
          plugin_discussions: yes

  # Main Metrics - Short
  shorter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/summary.svg
          committer_message: "📊 Updates metrics - summary"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: araguaci
          template: classic
          base: activity, community, repositories
          config_timezone: America/Sao_Paulo
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_traffic: yes
          plugin_lines: yes
          plugin_discussions: yes
          plugin_discussions_categories: no
