on:
  schedule:
    - cron: '0 */24 * * *' # every 48 hours
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          readme: './OUTPUT.md'
      - name: Check Status
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update OUTPUT.md"
          git push
          fi
