# Action to generate metrics using LowLighter/Metrics by Simon Lecoq

# All results are in SVG format, and commited to /assets/metrics/ in master branch.
# Split into multiple jobs, to prevent everything failing if one component errors,
# And to improve the loading and layout of /METRICS.md where the SVGs are displayed


name: Metrics
on:
  schedule:
    - cron: '40 23 * * *' # Run every evening, twenty mins before midnight
  workflow_dispatch: # Or when it's manually triggered
jobs:        
  # Main Metrics - Short
  shorter-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          filename: assets/metrics/summary.svg
          committer_message: "? Updates metrics - summary"
          committer_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          user: araguaci
          template: classic
          base: activity, community, repositories
          config_timezone: America/Sao_Paulo
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_traffic: yes
          plugin_lines: yes
          plugin_discussions: yes
          plugin_discussions_categories: no
